# Generated by Django 3.0.3 on 2020-03-14 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircrafts',
            fields=[
                ('aircraft_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ac_model', models.CharField(max_length=10)),
                ('ac_range', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('airport_name', models.TextField()),
                ('city', models.TextField()),
                ('coordinates', models.TextField()),
                ('timezone', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('book_ref', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('book_date', models.DateField()),
                ('total_amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flight_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('flight_no', models.CharField(max_length=10)),
                ('scheduled_departure', models.TimeField()),
                ('scheduled_arrival', models.TimeField()),
                ('status', models.CharField(max_length=100)),
                ('aircraft_code', models.IntegerField()),
                ('actual_departure', models.TimeField(default=models.TimeField())),
                ('actual_arrival', models.TimeField(default=models.TimeField())),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_airport', to='airtransport.Airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_airport', to='airtransport.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_no', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('passenger_id', models.IntegerField()),
                ('passenger_name', models.TextField(max_length=250)),
                ('contact_data', models.CharField(max_length=100, null=True)),
                ('book_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtransport.Bookings')),
            ],
        ),
        migrations.CreateModel(
            name='TicketFlights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_conditions', models.TextField()),
                ('fare_amount', models.IntegerField()),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtransport.Flights')),
                ('ticket_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtransport.Tickets')),
            ],
            options={
                'unique_together': {('ticket_no', 'ticket_no')},
            },
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_no', models.CharField(max_length=10)),
                ('fare_conditions', models.CharField(max_length=100)),
                ('aircraft_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtransport.Aircrafts')),
            ],
            options={
                'unique_together': {('aircraft_code', 'seats_no')},
            },
        ),
        migrations.CreateModel(
            name='BoardingPasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_no', models.PositiveIntegerField()),
                ('seat_no', models.CharField(max_length=10)),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtransport.Flights')),
                ('ticket_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtransport.Tickets')),
            ],
            options={
                'unique_together': {('ticket_no', 'flight_id')},
            },
        ),
    ]
