# Generated by Django 3.0.3 on 2020-03-14 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airtransport', '0002_auto_20200314_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='aircraft_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtransport.Aircrafts'),
        ),
    ]
