# Generated by Django 3.0.3 on 2020-03-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtransport', '0004_auto_20200314_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='actual_arrival',
            field=models.TimeField(blank=True, default=models.TimeField()),
        ),
        migrations.AlterField(
            model_name='flights',
            name='actual_departure',
            field=models.TimeField(blank=True, default=models.TimeField()),
        ),
    ]
