# Generated by Django 3.0.3 on 2020-04-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtransport', '0006_auto_20200314_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='actual_arrival',
            field=models.DateTimeField(default=models.DateTimeField()),
        ),
        migrations.AlterField(
            model_name='flights',
            name='actual_departure',
            field=models.DateTimeField(default=models.DateTimeField()),
        ),
        migrations.AlterField(
            model_name='flights',
            name='scheduled_arrival',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flights',
            name='scheduled_departure',
            field=models.DateTimeField(),
        ),
    ]
